----------------------------------------------------
----------------------------------------------------
-- THIS FILE WAS GENERATED BY VISUAL ELITE
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
----------------------------------------------------
----------------------------------------------------
-- GNU LESSER GENERAL PUBLIC LICENSE
----------------------------------------------------
-- This source file is free software; you can redistribute it and/or modify it
-- under the terms of the GNU Lesser General Public License as published by the
-- Free Software Foundation; either version 2.1 of the License, or (at your
-- option) any later version. This source is distributed in the hope that it
-- will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
-- of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- See the GNU Lesser General Public License for more details. You should have
-- received a copy of the GNU Lesser General Public License along with this
-- source; if not, download it from http://www.gnu.org/licenses/lgpl-2.1.html
----------------------------------------------------
----------------------------------------------------
--
--  Library Name :  GTP
--  Unit    Name :  GTP_3b4bTable
--  Unit    Type :  Truth Table
--
------------------------------------------------------

library ieee;
use ieee.STD_LOGIC_1164.all;
use ieee.NUMERIC_STD.all;
entity GTP_3b4bTable is
  port (
        In3b : in std_logic_vector(2 downto 0 );
        Out4b : out std_logic_vector(3 downto 0 );
        DatFlip : out std_logic;
        DispFlip : out std_logic
        );

end GTP_3b4bTable;


architecture GTP_3b4bTable of GTP_3b4bTable is


begin
  GTP_3b4bTable:
  process (In3b)
  begin

    if (In3b = "000") then
      Out4b <= "1011";
      DatFlip <= '1';
      DispFlip <= '1';
    --  Dx.0
    elsif (In3b = "001") then
      Out4b <= "1001";
      DatFlip <= '0';
      DispFlip <= '0';
    --  Dx.1
    elsif (In3b = "010") then
      Out4b <= "0101";
      DatFlip <= '0';
      DispFlip <= '0';
    --  Dx.2
    elsif (In3b = "011") then
      Out4b <= "1100";
      DatFlip <= '1';
      DispFlip <= '0';
    --  Dx.3
    elsif (In3b = "100") then
      Out4b <= "1101";
      DatFlip <= '1';
      DispFlip <= '1';
    --  Dx.4
    elsif (In3b = "101") then
      Out4b <= "1010";
      DatFlip <= '0';
      DispFlip <= '0';
    --  Dx.5
    elsif (In3b = "110") then
      Out4b <= "0110";
      DatFlip <= '0';
      DispFlip <= '0';
    --  Dx.6
    elsif (In3b = "111") then
      Out4b <= "1110";
      DatFlip <= '1';
      DispFlip <= '1';
    else
      --  Dx.7 (Primary)

      Out4b <= "0000";
      DatFlip <= '0';
      DispFlip <= '0';
    end if ;
  end process GTP_3b4bTable;

end GTP_3b4bTable;

