----------------------------------------------------
----------------------------------------------------
-- THIS FILE WAS GENERATED BY VISUAL ELITE
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
----------------------------------------------------
----------------------------------------------------
-- GNU LESSER GENERAL PUBLIC LICENSE
----------------------------------------------------
-- This source file is free software; you can redistribute it and/or modify it
-- under the terms of the GNU Lesser General Public License as published by the
-- Free Software Foundation; either version 2.1 of the License, or (at your
-- option) any later version. This source is distributed in the hope that it
-- will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
-- of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- See the GNU Lesser General Public License for more details. You should have
-- received a copy of the GNU Lesser General Public License along with this
-- source; if not, download it from http://www.gnu.org/licenses/lgpl-2.1.html
----------------------------------------------------
----------------------------------------------------
--
--  Library Name :  GTP
--  Unit    Name :  GTP_Dx7Table
--  Unit    Type :  Truth Table
--
------------------------------------------------------

library ieee;
use ieee.STD_LOGIC_1164.all;
use ieee.NUMERIC_STD.all;
entity GTP_Dx7Table is
  port (
        In4b : in std_logic_vector(3 downto 0 );
        Out4b : out std_logic_vector(3 downto 0 );
        In6b : in std_logic_vector(5 downto 0 )
        );

end GTP_Dx7Table;


architecture GTP_Dx7Table of GTP_Dx7Table is


begin
  GTP_Dx7Table:
  process (In4b, In6b)
  begin

    if (In4b = "1110") AND
       (In6b = "100011") then
      Out4b <= "0111";
    --  D17.7-
    elsif
          (In4b = "1110") AND
          (In6b = "010011") then
      Out4b <= "0111";
    --  D18.7-
    elsif
          (In4b = "1110") AND
          (In6b = "001011") then
      Out4b <= "0111";
    --  D20.7-
    elsif
          (In4b = "0001") AND
          (In6b = "110100") then
      Out4b <= "1000";
    --  D11.7+
    elsif
          (In4b = "0001") AND
          (In6b = "101100") then
      Out4b <= "1000";
    --  D13.7+
    elsif
          (In4b = "0001") AND
          (In6b = "011100") then
      Out4b <= "1000";
    else
      --  D14.7+

      Out4b <= In4b;
    end if ;
  end process GTP_Dx7Table;

end GTP_Dx7Table;

