----------------------------------------------------
----------------------------------------------------
-- THIS FILE WAS GENERATED BY VISUAL ELITE
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
----------------------------------------------------
----------------------------------------------------
-- GNU LESSER GENERAL PUBLIC LICENSE
----------------------------------------------------
-- This source file is free software; you can redistribute it and/or modify it
-- under the terms of the GNU Lesser General Public License as published by the
-- Free Software Foundation; either version 2.1 of the License, or (at your
-- option) any later version. This source is distributed in the hope that it
-- will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
-- of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- See the GNU Lesser General Public License for more details. You should have
-- received a copy of the GNU Lesser General Public License along with this
-- source; if not, download it from http://www.gnu.org/licenses/lgpl-2.1.html
----------------------------------------------------
----------------------------------------------------
--
--  Library Name :  CommonVisual
--  Unit    Name :  NegEdge
--  Unit    Type :  Text Unit
--
------------------------------------------------------
------------------------------------------
------------------------------------------
-- Date        : Thu Jun 12 10:26:24 2003
--
-- Author      : J.C.Molendijk
--
-- Company     :
--
-- Description : A Negative Edge Detector
--
------------------------------------------
------------------------------------------
library ieee;
use ieee.std_logic_1164.all;

entity  NegEdge  is

port(Clk,SigIn : in  std_logic;
     NEdg      : out std_logic);

end;

------------------------------------------
------------------------------------------
-- Date        : Thu Jun 12 10:29:33 2003
--
-- Author      : J.C.Molendijk
--
-- Company     :
--
-- Description : A Negative Edge Detector
--
------------------------------------------
------------------------------------------
architecture  V1  of  NegEdge  is

signal SR: std_logic_vector(1 downto 0):="00";

begin

  process(Clk)
    begin
      if Clk'event and Clk = '1'
        then
          SR(1) <= SR(0);
          SR(0) <= SigIn;
        if SR(1) = '1' and SR(0) = '0'
          then NEdg <= '1';
          else NEdg <= '0';
        end if;
      end if;
    end process;

end;

